// generated by unplugin-svelte-components
// We suggest you to commit this file into source control
declare global {
	const Counter: typeof import('./lib/components/Counter.svelte')['default']
	const Footer: typeof import('./lib/components/Footer.svelte')['default']
	const Hello: typeof import('./lib/components/Hello.svelte')['default']
	const Input: typeof import('./lib/components/Input.svelte')['default']
}

export {}
