// generated by unplugin-svelte-components
// We suggest you to commit this file into source control
declare global {
	const Counter: typeof import('./components/Counter.svelte')['default'];
	const Header: typeof import('./components/Header.svelte')['default'];
}

export {};
